services:
  eggnet-site:
    image: ghcr.io/hung-eggie-do-covergo/eggnet-site:fd9c9554c5503aff5e779a530fb3b4a5a2589c5b
    container_name: eggnet-site
    restart: unless-stopped
    ports:
      - "8093:80"
    pull_policy: always
