services:
  eggnet-site:
    image: ghcr.io/hung-eggie-do-covergo/eggnet-site:bd0b7610358767074bbdb6ce1544868c93c0bfae
    container_name: eggnet-site
    restart: unless-stopped
    ports:
      - "8093:80"
    pull_policy: always
