services:
  eggnet-site:
    image: ghcr.io/hung-eggie-do-covergo/eggnet-site:19f973401da9bf5c6025c5680b6b36879c62206e
    container_name: eggnet-site
    restart: unless-stopped
    ports:
      - "8093:80"
    pull_policy: always
